kind: project
metadata:
  name: stress-project-amite
spec:
  functions:
  - url: jobs_func.py
    name: normal-job-sec
    kind: job
    image: mlrun/mlrun
    handler: func_sec
  - url: jobs_func.py
    name: normal-job-min
    kind: job
    image: mlrun/mlrun
    handler: func_min
  - url: jobs_func.py
    name: normal-job-hour
    kind: job
    image: mlrun/mlrun
    handler: func_hour
  - url: jobs_func.py
    name: artifact-job
    kind: job
    image: mlrun/mlrun
    handler: func_artifact
  - url: jobs_func.py
    name: dataset-job
    kind: job
    image: mlrun/mlrun
    handler: func_dataset
  - url: spark_jobs_func.py
    name: spark-job
    kind: spark
    image: mlrun/mlrun
    handler: spark_handler
  - url: ./dask_jobs_func.py
    name: dask-func
    kind: job
    image: mlrun/mlrun
    handler: train
  - url: nuclio_func.py
    name: nuclio-func
    kind: nuclio
    image: mlrun/mlrun
    handler: handler
  - url: log_models.py
    name: log-models-job
    kind: job
    image: mlrun/mlrun
    handler: log_n_models
    requirements:
    - scikit-learn
  - url: serving_creator_func.py
    name: serving-creator-job
    kind: job
    image: mlrun/mlrun
    handler: deploy_serving_functions
  workflows:
  - path: workflow.py
    name: workflow-func
  artifacts: []
  conda: ''
  source: ''
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
